### PR TITLE
Assign .github repository to rainmakers

### PR DESCRIPTION
**Pull request by marians**

### CODE REVIEW

**Comment by marians** [comment]
Hey @tommyhobin , would you say that it makes sense to assign this repo's ownership to nifflers? If yes, please approve the PR. Thanks!

**Comment by tommyhobin** [comment]
@marians if it is important to have a Niffler Team member approve this PR, you would need to include one of them. I am the PO of the Rainmakers team.

... I mean it looks fine to me. Lemme know if you want that - otherwise, I can approve.

**Comment by marians** [comment]
Sorry, I confused the teams! Should rather go to Rainmakers I think. Will change.

**Review by tommyhobin — APPROVED** [review]
LGTM

**Pull request merged**
